app: 
  run_mode: "debug"
  cancel_timeout: "5s"

server:
  http_port: 8080
  read_header_timeout: "5s"

mysql:
  user: "mysql"
  password: "example"
  host: "mysql"
  port: 3306
  name: "LVD"
  debug: true


redis:
  user: ""
  password: ""
  host: "redis"
  port: 6379
  database: 0
  idleTimeout: "200s"

log:
  log_path: "../log/app.log"
  application_name: "LVD"
  level: "INFO"
  debug: true

jwt: 
  expiration: "24h"